# Generated by Django 4.1.7 on 2023-04-16 07:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_alter_tourimage_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='background',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
