# Generated by Django 4.1.7 on 2023-03-17 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_post_role_usertour_tourimage_tourcomment_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='tourism.role'),
        ),
    ]
