# Generated by Django 4.1.7 on 2023-04-16 07:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_tour_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourimage',
            name='value',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
