# Generated by Django 4.1.7 on 2023-04-16 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_alter_tourimage_value_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeComment',
            new_name='PostLike',
        ),
    ]
