# Generated by Django 4.1.7 on 2023-03-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
