# Generated by Django 4.1.7 on 2023-04-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_rename_likecomment_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
