# Generated by Django 4.1.7 on 2023-04-23 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0009_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertour',
            name='payment_method',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='tourism.post'),
        ),
    ]
