# Generated by Django 4.1.7 on 2023-04-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0010_usertour_payment_method_alter_postlike_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='number_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usertour',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
