# Generated by Django 4.1.7 on 2023-04-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0011_alter_tour_number_rate_alter_usertour_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, 'female'), (1, 'male'), (2, 'not specified')]),
        ),
    ]
