# Generated by Django 4.1.7 on 2023-04-26 08:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0012_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1681630820/agk5titgearqrmlzgjgx.png', max_length=255, verbose_name='image'),
        ),
    ]
