# Generated by Django 4.1.7 on 2023-05-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0013_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'admin'), (1, 'staff'), (2, 'customer')], default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'female'), (1, 'male'), (2, 'not specified')]),
        ),
    ]
