# Generated by Django 4.1.7 on 2023-05-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0014_user_role_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertour',
            name='total_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
