# Generated by Django 4.1.7 on 2023-05-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0015_alter_usertour_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertour',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
